### ISSUE TITLE
incorrect entries for modalities available

### ISSUE THREAD

**Issue by poldrack** [OpenNeuroOrg/openneuro#1063]
it appears that the Available Modalities listing on the datasets page is listing things that are not really data modalities.  for example, for many datasets it is listing /participants and for EEG data it is listing coordsystem, electrodes, channels, events, ieeg, scans.  It also seems to be listing the full contents of the stimuli directory.  we probably need to come up with a heuristic so that we can provide a more useful summary of what is available

**Comment by chrisgorgo** [comment]
This has been fixed in https://github.com/bids-standard/bids-validator/issues/704 and will be part of the new `bids-validator` release. After deploying it on OpenNeuro do we need to regenerate the summaries for all datasets?

**Comment by nellh** [comment]
Drafts update whenever a change is made but any snapshots will need a script written to rerun them, since we consider snapshot validation immutable. We record which version of the validator was used, so we can just rerun the snapshots created with the one release which was on OpenNeuro with this bug.

**Comment by nellh** [comment]
bids-validator summary modalities have been updated for the most recent snapshot of most datasets.
