### ISSUE TITLE
Add "Open in BrainLife.io" button to dataset page

### ISSUE THREAD

**Issue by effigies** [OpenNeuroOrg/openneuro#1127]
[BrainLife](https://brainlife.io) is making a number of OpenNeuro datasets available for their users at https://brainlife.io/project/. For those datasets which are available, we'd like to add a "Open in BrainLife.io" button next to the "Download" button.

I've mocked up a button for DS000003:

<img width="663" alt="Screen Shot 2019-05-16 at 13 45 36" src="https://user-images.githubusercontent.com/83442/57878638-74f76880-77e8-11e9-8db4-d906434f9448.png">

I did this by duplicating the download button, adding `margin-right: 1em` to the button CSS, and adding `display: flex` to the containing' `<div>`'s CSS.

The target URL for ds00ABCD would be https://brainlife.io/openneuro/ds00ABCD.

BrainLife is not automatically indexing all OpenNeuro datasets, so we'll need some way to periodically poll which are available.

cc @soichih

**Comment by franklin-feingold** [comment]
Looks good!

@soichih - when you add openneuro datasets to brainlife (which looks great!) would it be possible to be notified or have a weekly/biweekly summary of additions so the updates can be better documented and tracked for everyone?

**Comment by soichih** [comment]
@franklin-feingold Thanks! Yes, I can store and publish the information somewhere. Do you have any suggestion on format/location? 

Since I simply *link* to openneuro datasets, I can technically just import *all* datasets.. but for now I am only crawling datasets with >30 downloads to keep the list of openeuro datasets short-ish. The importing is triggered by cron right now and I can run it as often as necessary. In the near future, however, I am planning to import openneuro datasets on-demand - triggered by user wanting to access it. In a sense, you can just assume that all openneuro datasets are imported on brainlife.

For the "Open in brainlife.io" button, would it be better to call it "Analyze on brainlife.io" instead? Also, since most openneuro users won't know what brainlife is, is there any way to add a small text explaining what brainlife is? I think you could show something like..

(Analyze on brainlife.io)  * brainlife.io can run various data processing tools such as fmriprep, freesurfer, mrtrix and many other apps to analyze and visualize your data.

**Comment by franklin-feingold** [comment]
Thank you! @ckrountree is there a format/place that would work best for you for tracking and documenting? 

I think that is a good plan to move toward full support.

+1 for "Analyze on brainlife.io" and small text explaining what brainlife is

**Comment by ckrountree** [comment]
@franklin-feingold I think that GitHub is the best place to document/track these additions.  In regards to this button, since we will be adding a few of these types of buttons, this would greatly benefit from a design overview.  We can have @trevor-squishy look at this and figure out the best placement for these.  Four buttons across the same plane will look crowded (though, two look nice).

**Comment by nellh** [comment]
@effigies @soichih Is there an API call to check if a given snapshot is available on Brainlife? Either per snapshot or in bulk?

**Comment by soichih** [comment]
@nellh Yes, you can query it via our REST API.

```
curl -v https://brainlife.io/api/warehouse/project?find='\{"openneuro.dataset_id":"ds000117"\}'
```

However, this is not a documented/advertised way to tell if OpenNeuro projects exists or not.. but it *should* work. Also, if the dataset isn't imported to brainlife yet, the redirect link will still work (although currently, it simply points to a page that says "This dataset is not yet exposed through brainlife.io.") so I don't really think you have to worry about if the dataset is already imported or not. In the future, I am thinking about importing the datasets when it is first requested through this URL so that you can assume that all OpenNeuro projects are already imported to Brainlife (if not, it will on the fly).
