### ISSUE TITLE
Create generic error boundary and show FreshDesk widget on errors

### ISSUE THREAD

**Issue by ckrountree** [OpenNeuroOrg/openneuro#1133]
Figure out error boundaries so we can throw up an error message for users to contact support (FreshDesk).  Perhaps, reference the SENTRY ID in the support form (ie: "Please provide this (SENTRY) ID# in the support ticket.")

**Comment by nellh** [comment]
Here's how to prepopulate a field for the Freshdesk widget. https://support.freshdesk.com/support/solutions/articles/154064-pre-populating-feedback-widget-form

For where this needs to go, above the query components for the dashboards and datasets will catch most errors. On the datasets page: comments, files, validation, and the editable fields should each be under their own boundary.

The UI needs to be separate from the context, since some places this will be useful are small widgets. A good approach would be the error boundary itself renders a responsive message at various sizes but triggers the support modal above this. That way if something like comments fail to load, you can still view the rest of the dataset page but you do have the opportunity to file a support request with the prefilled Sentry id.
