### ISSUE TITLE
Changes to dataset_description.json are not saved in snapshot

### ISSUE THREAD

**Issue by effigies** [OpenNeuroOrg/openneuro#1138]
Updating `dataset_description.json` through the web interface or by uploading a new copy will change values in the draft dataset, but snapshots will not contain the changes, instead reverting to the previous version.

Also, using the `Edit` option to edit the values produces a throbber that goes on for minutes (I didn't leave it to see if it ever refreshed).

Both of these issues were reported by user with a large dataset and reproduced on the very small ds001024 on the dev server. The user tried this with the "HowToAcknowledge" field, and I tried it with the "License" field.

**Comment by effigies** [comment]
This has appeared in the following Freshdesk tickets:

* 244
* 257

**Comment by franklin-feingold** [comment]
This issue has also appeared in Freshdesk ticket 256 (ds1882)

256 references the dataset DOI (the user hardcoded it into the dataset_description.json), the result is in the snapshot it has the dataset DOI appear as 'null'

**Comment by effigies** [comment]
@franklin-feingold To confirm, the user tried removing the DOI, creating a snapshot, and that still did not resolve their problem?

**Comment by franklin-feingold** [comment]
This is currently being tested - will update once this path is completed

**Comment by nellh** [comment]
I'm not seeing this with a small dataset on dev. My guess here is that the snapshot is created before the edit has been committed. Ordering of writes is enforced but the dataset_description.json read is not. The old dataset_description.json gets read and modified with the DOI before the pending edit has been committed, meaning the edit gets applied and then removed shortly after.

Possible fix is to make the dataset_description edit atomic, perform the read and the write in one step that is queued in order.

**Comment by effigies** [comment]
Interesting. In 244, the user reported waiting a day with the dataset_description update in draft before trying to create a snapshot, and the issue still occurred there. I did not wait very long with the small dataset on dev.

**Comment by franklin-feingold** [comment]
I am seeing this path. The user deleted the coded DOI from the dataset_description.json and tried to make another snapshot but the DOI was not added (https://openneuro.org/datasets/ds001882/versions/1.0.5) this also causes an error on the validation because of a misformatted dataset_description.json. 

I have another case - (https://openneuro.org/datasets/ds001934/versions/1.0.2). In the drafts there is a link and doi for the publication in the references/links field and accurately shows it in the drafts, but upon making a snapshot it reverts back to a previous dataset_description.json. Perhaps could be not giving enough for the update to occur before a snapshot is created

**Comment by david-nishi** [comment]
#1164 and OpenNeuroOrg/datalad-service#90
