### ISSUE TITLE
Downloading datasets from AWS does not retrieve latest version

### ISSUE THREAD

**Issue by effigies** [OpenNeuroOrg/openneuro#1154]
See, for example, ds001769.

```
$ aws s3 sync --no-sign-request s3://openneuro.org/ds001769 ds001769-download/
...
$ grep DatasetDOI ds001769-download/dataset_description.json
    "DatasetDOI": "10.18112/openneuro.ds001769.v1.1.0",
```

With datalad:

```
$ datalad install https://github.com/OpenNeuroDatasets/ds001769.git
...
$ grep DatasetDOI ds001769/dataset_description.json
    "DatasetDOI": "10.18112/openneuro.ds001769.v1.2.0"
```

**Comment by lukassnoek** [comment]
I'm not sure whether this is an `awscli` issue or one from Openneuro, but I'm also encountering this issue when trying to download the latest version of ds002547 (snapshot 1.1.0):

```
aws s3 sync --no-sign-request s3://openneuro.org/ds002547 test_dir --exclude "*" --include "*dataset_description.json"
cat test_dir/dataset_description.json
...
DatasetDOI": "10.18112/openneuro.ds002547.v1.0.0"
...
```

Best,
Lukas

**Comment by jcohenadad** [comment]
also encountered this issue with https://openneuro.org/datasets/ds002900
i ran (on 2020-06-27 16:32:04 on OSX 10.14):
~~~
aws s3 sync --no-sign-request s3://openneuro.org/ds002900 ds002900-download/
~~~
and the CHANGE file indicated that it was version 1.0.2 instead of the latest 1.0.4.

Also: it would be nice to have a way to verify the snapshot version (instead of relying on the CHANGE file, which could be manually modified and is an indirect way of verifying snapshot version)

thanks!

**Comment by effigies** [comment]
The snapshot version should generally be encoded in the dataset_description.json. This is set by OpenNeuro directly during the snapshot process.

**Comment by nellh** [comment]
This is resolved for the current set of public datasets, we may see it on some older private datasets if they are made public but I think new issues should be made for that.
