### ISSUE TITLE
Address general mobile layout issues

### ISSUE THREAD

**Issue by ckrountree** [OpenNeuroOrg/openneuro#1160]

**Comment by exbotanical** [comment]
I've reviewed the site and its various routes / functionality using a variety of common browser clients on a variety of mobile devices (i.e. Galaxy S7, iPhone X, et al). Follows is an accounting of the outstanding cosmetic and functional issues we should address in the 'mobile incarnation' of OpenNeuro:

**Header/Menu** 

- The header/menu has a considerable overflow beyond the view. Because the header persists across all pages, so, too, do its stylings. (see #1329)
- The dropdown menu does not close when an item is selected. The user has to do this manually, lest the requested page be blocked by it. (see #1330)

**Homepage**

- The background container is offset on the right side; a gray outer background appears in concert with the scroll bar.
- The "OpenNeuro" title (`div`, `span`; class "logo-text") flows outside of the aforementioned background container. 
- Largely cosmetic and perhaps inconsequential, the 'most active' and 'recently published' green footer containers blend together. I believe their importance could be elucidated were we to either add a `space-between` attribute to separate them a bit _OR_ add emphasis to their respective titles using heaver font weight. 
    - These lists are populated with five items, each. Given the front page is quite the long scroll on mobile as it is, perhaps we could limit this to three items, each. 

(see #1331)

**Public Dashboard**

- Perhaps sorting could be a dropdown menu? The items are stacking and occupying valuable view-space on mobile.  (see #1332)
- The `h4` "dataset-name" elements (dataset titles) overflow their containers.  (see #1333)
- The metrics and accompanying icons overflow (and are hidden/cut off by) their containers. (see #1334) 
- Like the metrics, the dataset summary is being pushed out of the view and hidden. These items should be included in the container and most likely stacked so as to fit nicely. (see #1335)
- For consideration: Do we want to allow infinite scrolling or pagination on mobile (perhaps even on desktop)? Despite my being a relative neophyte to GraphQL, I suspect that adding pagination would conserve load-times, as less data would need to be fetched when loading the public dashboard. (see #1020 and Nell's comment: https://github.com/OpenNeuroOrg/openneuro/issues/1160#issuecomment-542356742)
- Search returns several links to a dataset: one for the dataset itself, and one for each of its snapshots. If I recall correctly, however, we will be looking at this search feature in the imminent future; perhaps this can be fixed then. (see #1336)

**Dataset Page**

I recommend we prioritize the focus of mobile-oriented development _here_. As the primary content of OpenNeuro, the dataset pages should - at the very least - be navigable. 

- Content overflows at: `h1`, panel heading, metadata `h2`, `p` (see #1337)
- The file tree "dataset files" sees a notable overflow and leaves the view entirely in some places, which could prevent user access to deeply nested directories (the more nested, the further to the right of the view). (see #1338)
- A low-priority item, perhaps the metadata could be in a dropdown? It does consume a significant amount of the page, making the dataset view lengthy. (see #1339)

**Data**

- .gz files load remarkably well on mobile, however the Papaya tool has a few styling issues. I am not familiar enough with Papaya to know whether or not it supports mobile usage. This may not be so pertinent an issue, though - especially if we add functionality for users to email download links and/or bookmark/pin datasets for download when on desktop.

**Support**

- The FreshDesk widget is not in any way formatted for mobile. Further, once loaded, it cannot be closed; the user must reload the site to "get out of it". Perhaps this is an issue that could be coupled with [1210](https://github.com/OpenNeuroOrg/openneuro/issues/1210) provided it warrants restyling the widget (which seems to be the case, at a glance). (added this issue to #1210)

**FAQ**

The FAQ page is surprisingly unadulterated in mobile view. It's rather responsive, with the minor exception of the `>>` arrows that precede each title element. This isn't a pressing issue. (see #1340)

**Sign-in**

- Our auth/sign-in widget, like Freshdesk, is not optimized for mobile view. There may be some devices whereon the login buttons aren't even accessible. I'd venture a guess that this is a considerable _minority_ of devices, but it is a rather significant _cosmetic_ issue. (see https://github.com/OpenNeuroOrg/openneuro/issues/1160#issuecomment-542851748)

**Summary**

In summation, it is my opinion that our priority - insofar as cosmetic issues is concerned - lies in the dataset pages, as they comprise our content. Our mobile users cannot reasonably interact with the content as-is, so I would recommend the styling be refactored so as to be responsive. On par with this priority (or close to it, at least) is adding the download bookmark/email reminder as Eric has suggested. An ancillary 'high priority' item is probably improving SEO, though I'm not yet fully aware which parts of the app contribute to (or detract from) this. 

Next, I would prioritize the widgets (FreshDesk and Login), as these are concerns of accessibility. 

Last...I don't know if the question of infinite scrolling versus pagination has been discussed, but perhaps it should be looked at again; we could provide our users far more efficient rendering by fetching only, say, 20 dataset entries at a time (i.e. per page), if possible.

**Comment by exbotanical** [comment]
An additional note: this is largely dependent on which direction we decide to go in regarding browser client support, but using CSS Grid would be a really great solution to many of the aforementioned issues. Maybe something we can discuss in the near future? (I believe there was a conversation on the CRN Slack channel about this, concentrating support to Chrome)

**Comment by ckrountree** [comment]
@MatthewZito one thing to keep in mind is that this is made somewhat more complex because the app is built around Bootstrap 3, which isn’t being developed anymore.  However, I believe that, as things get refactored, Bootstrap 3 is being removed.  Maybe @nellh can confirm/deny this?

**Comment by nellh** [comment]
I think we would like to move away from Bootstrap 3 if possible. It's not particularly blocking mobile fixes though, many of the styles were just written without mobile in mind, it's not a limitation of Bootstrap 3. The bigger issue with the CSS as it currently stands is not well isolated and follows several different styles (global inheritance and modular CSS mixed together). This leads to an excess of CSS and some poorly performing elements, particularly when the device used has a low end GPU.

@MatthewZito FYI the infinite scrolling implementation loads 25 datasets at a time and culls unused markup for mobile already. #1020 describes an optimization that would help a bit more on mobile.

**Comment by ckrountree** [comment]
> Our auth/sign-in widget, like Freshdesk, is not optimized for mobile view. There may be some devices whereon the login buttons aren't even accessible. I'd venture a guess that this is a considerable minority of devices, but it is a rather significant cosmetic issue.

NOTE:  this is not for the Google or ORCID signin buttons.  This is the login from the nav-hamburger.  However, this may be a moot point if we remove the hamburger (Bootstrap 3 design).
