### ISSUE TITLE
Datalad not fetching latest dataset version

### ISSUE THREAD

**Issue by franklin-feingold** [OpenNeuroOrg/openneuro#1200]
This issue was found on [dataset 1919](https://openneuro.org/datasets/ds001919/versions/1.0.4). The datalad version is fetching version 1.0.3 where the public version is on 1.0.4. The validation is also pending on this dataset. More information can found on [this NeuroStars post](https://neurostars.org/t/cannot-find-latest-version-when-updating-datalad-datasets/4679).

**Comment by effigies** [comment]
Semi-related to #1154.

**Comment by nellh** [comment]
This should be resolved now, I believe this was related to service failures we were experiencing before the switch to the new hosting setup.

**Comment by effigies** [comment]
Installing from GitHub works for me.

**Comment by jcohenadad** [comment]
Not sure if this is a related issue, but the URL on the OpenNeuro website does not point to the latest version of the dataset (tested on 2019-09-25 at 17:12:10):

![Screen Shot 2019-09-25 at 5 11 32 PM](https://user-images.githubusercontent.com/2482071/65640100-939c1600-dfb7-11e9-89e9-dede6a554c60.png)

**Comment by nellh** [comment]
> Not sure if this is a related issue, but the URL on the OpenNeuro website does not point to the latest version of the dataset (tested on 2019-09-25 at 17:12:10):
> 
> ![Screen Shot 2019-09-25 at 5 11 32 PM](https://user-images.githubusercontent.com/2482071/65640100-939c1600-dfb7-11e9-89e9-dede6a554c60.png)

Hi @jcohenadad - thanks for the report. These search results currently come from Google custom search and we have little control over them. We do have a few issues open to improve the search metadata so that Google has an easier time picking up different snapshots which may help. We will also be adding some new search functionality soon which will give us better control over the results to improve things like this.
