### ISSUE TITLE
Partial datasets draft page disappears

### ISSUE THREAD

**Issue by effigies** [OpenNeuroOrg/openneuro#1222]
https://openneuro.org/datasets/ds002041

**Comment by franklin-feingold** [comment]
we have another case of this - https://openneuro.org/datasets/ds002078
https://openneuro.org/datasets/ds000248/versions/00001
https://openneuro.org/datasets/ds002087/versions/1.0.0
https://openneuro.org/datasets/ds001942/versions/1.0.0

**Comment by nellh** [comment]
Narrowed this down some, it's caused by incomplete uploads hiding the draft. You can fix this from the dashboard by resuming the upload as a workaround.

**Comment by franklin-feingold** [comment]
to clarify - this would be from the user? May we be able to do an action from our side to fix this?

**Comment by nellh** [comment]
Anyone with admin access can do so but I think a better fix is to do two things, figure out what the cache inconsistency is caused by (I'd say that's the problem we're looking at in this issue) and implement some way to decide if you want to throw out uncommitted changes or not (really what the "partial" state is).

**Comment by nellh** [comment]
Looks like the direct (#1238) and several indirect fixes have resolved this issue.
