### ISSUE TITLE
Fix main page participant count

### ISSUE THREAD

**Issue by franklin-feingold** [OpenNeuroOrg/openneuro#1270]
Following up on the mismatch between the participant numbers on my metadata and the front of ON. I was sent over the dataset by subjects that is making up that number and found where the discrepancies lie. Appears to be about 31 datasets that are missing from that number and several that are mismatched. 

Work in progress:
- I am investigating those 31 datasets to see if there is a consistent thread across them.

**Comment by nellh** [comment]
These are likely just missing validation in the latest snapshot, which is where we pull the count from.

**Comment by franklin-feingold** [comment]
Following up on this - I've tried to regenerate our participant count displayed on our main page using GraphQL to query our database. My approach was to first run a GraphQL query to return subject lists for the latest snapshot from every public dataset. I can take the length of this subject list and sum over the datasets to construct our participant count. For many of the problematic datasets, I resolved the validator and minted a new snapshot. This process did not resolve our counts. I fixed several datasets, but the count did not increase (giving a few days for this number to be recalculated). Our current count is about ~700 participants off. I can run further tests but it was not clear what other points I can hit from my side to dig further into this. 

Note: according to my curated [metadata sheet](https://docs.google.com/spreadsheets/d/1rsVlKg0vBzkx7XUGK4joky9cM8umtkQRpJ2Y-5d6x7c/edit#gid=1226202843) there are another ~600 participants that aren't being caught by GraphQL either - I am still targeting and remedying these

@ckrountree

**Comment by nellh** [comment]
I went through and revalidated this query with some more diverse data from production. Looks like the group by step is sorting the snapshots wrong, so you get the earliest snapshot with validation. This looks fairly correct for some of the data tested because earlier snapshots are missing validation on some of these older datasets but testing with more datasets it becomes apparent that the earlier snapshots are being counted.

Rerunning with this fix on production we get:
12114 -> 12947

@franklin-feingold  Is 12947 about what you are expecting?

**Comment by franklin-feingold** [comment]
thank you for taking a look - yep! that gets us much closer to resolving our count. I will be able to more specifically target our lingering problematic dataset

**Comment by franklin-feingold** [comment]
Today's release has resolved this
