### ISSUE TITLE
problem uploading large files

### ISSUE THREAD

**Issue by poldrack** [OpenNeuroOrg/openneuro#13]
I am trying to upload a dataset that includes a large fMRI data file (~487 MB) and the upload has failed twice on that file.  This is for https://openneuro.org/datasets/ds001040

**Comment by nellh** [comment]
@sadevp Since you are seeing this too, can you record a HAR file with Chrome and send that to me to help debug the root cause of this issue?

Here's some [instructions for recording the HAR file](https://community.box.com/t5/Managing-Content-Troubleshooting/How-to-Generate-a-HAR-File-in-Chrome-IE-or-Firefox/ta-p/366). Since this will contain some private information, please share it without attaching it to the issue.

**Comment by sadevp** [comment]
Attachments available until Oct 12, 2017
Hi Nell,

The file is too large to share over email.

Thanks,
Sadev

Click to Download<link removed>
chrome_console.log
35 KB
Click to Download<link removed>
openneuro.org.har
95.6 MB




On Sep 12, 2017, at 11:21 AM, Nell Hardcastle <notifications@github.com<mailto:notifications@github.com>> wrote:


@sadevp<https://github.com/sadevp> Since you are seeing this too, can you record a HAR file with Chrome and send that to me to help debug the root cause of this issue?

Here's some instructions for recording the HAR file<https://community.box.com/t5/Managing-Content-Troubleshooting/How-to-Generate-a-HAR-File-in-Chrome-IE-or-Firefox/ta-p/366>. Since this will contain some private information, please share it without attaching it to the issue.

**Comment by nellh** [comment]
@sadevp Thanks, I've downloaded those files and removed the links from the issue.

**Comment by suyashdb** [comment]
i tried uploading ds208 three times. Following is the description what happened each time. 

In each of the case below my computer didn't sleep and i was on wired internet connection.

Try 1: Failed  
Upload it via `normal chrome` browser with lot of plugins.  All Errors were mostly for plugins expect this one: `Failed to load resource: net::ERR_NETWORK_CHANGED
/api/projects/202020206473303031303638/files Failed to load resource:`

Try 2: Failed 
Uploaded via `incognito` window(without plugins). Got same network error
`Failed to load resource: net::ERR_NETWORK_CHANGED
/api/projects/202020206473303031303638/files Failed to load resource:`

Try3: Success 
Incognito window. Success No errors

**Comment by nellh** [comment]
@suyashdb Thanks for the information. What OS and version of Chrome are you using? ERR_NETWORK_CHANGED is often associated with misconfiguration of the network you are on or user actions such as joining a VPN but it's a situation we should handle better in the upload.

**Comment by suyashdb** [comment]
@nellh  i am on Mac OS 10.11.6 and chrome Version 60.0.3112.113. I am sure about not joining a VPN network during the time of upload. 
Please let me know if more information is required to keep finger on the bug/issue.

**Comment by sadevp** [comment]
I experienced this issue again today when uploading ds000222, please see attached screenshot. I am uploading in Chrome without any plugins installed. 

I am using Mac OS version 10.12.6, and Chrome Version Version 60.0.3112.113

![screen shot 2017-09-18 at 11 15 41 am](https://user-images.githubusercontent.com/26071772/30557351-d3ac4bc4-9c62-11e7-829c-020fc1d57ade.png)

**Comment by nellh** [comment]
A patch to enable retries during upload might help with this and is available to test on the [dev server](https://openneuro.dev.sqm.io/). I haven't been able to reproduce this exact error, so please test and let me know if this helps.

**Comment by nellh** [comment]
Please reopen this if you are still having this issue. The retry fix is deployed on production.

**Comment by chrisgorgo** [comment]
I hear from users things have improved in terms of uploads. Thanks!
