### ISSUE TITLE
Implement background fetch for downloads

### ISSUE THREAD

**Issue by nellh** [OpenNeuroOrg/openneuro#1356]
This would allow for better download performance and reliability but is currently only implemented by Chrome and other Blink browsers.

The implementation needs to detect if a browser supports this feature and fall back to fetch or xhr if it does not.

**Comment by ckrountree** [comment]
Related: Deeper discussion how this plays in the big picture. https://github.com/OpenNeuroOrg/openneuro/issues/1344#issuecomment-545605251

**Comment by ckrountree** [comment]
Background fetch has been implemented but it is not being used because it didn't work well in Chrome 85 (current release of Chrome). 
Background fetch is ~75% of the implementation. So, with the current implementation, it wouldn't show any upload progress but turning it on should successfully upload once Chrome fixes it.

**Comment by ckrountree** [comment]
After implementing a rough version of this, we found it isn't really possible with the current browser APIs without making multiple copies of each file. This is incredibly inefficient.  Instead we should implement a progress indicator for the native file downloads.
