### ISSUE TITLE
Implement background fetch for uploads

### ISSUE THREAD

**Issue by nellh** [OpenNeuroOrg/openneuro#1358]
Rework the current uploader implementation to support using the background fetch API if available.

**Comment by ckrountree** [comment]
Background fetch has been implemented but it is not being used because it didn't work well in Chrome 85 (current release of Chrome).
Background fetch is ~75% of the implementation. So, with the current implementation, it wouldn't show any upload progress but turning it on should successfully upload once Chrome fixes it.

**Comment by nellh** [comment]
No Firefox support still, I think this may not be useful.
