### ISSUE TITLE
ECS hosts run out of metadata space under load

### ISSUE THREAD

**Issue by nellh** [OpenNeuroOrg/openneuro#138]
When job density is high, we're running into the metadata space limits. This needs a compute environment update with a new AMI to fix this. I'm including a monitoring script so we can observe the disk space over time.

**Comment by nellh** [comment]
Testing the new AMI with 95% data, 5% metadata instead of 99% data, 1% metadata. This should eliminate the metadata bottleneck even under heavy volume usage.

**Comment by nellh** [comment]
This is deployed now.

**Comment by sadevp** [comment]
FMRIPrep was rerun on these datasets after the fix was deployed, but are still producing this error. I am rerunning again 107 and 52 again as a test, and will let you know if it succeeds.

https://openneuro.org/datasets/ds000107/versions/00001
https://openneuro.org/datasets/ds000109/versions/00001
https://openneuro.org/datasets/ds000110/versions/00001
https://openneuro.org/datasets/ds000052/versions/00001?app=MRIQC&version=33&job=5720deb7-deef-4065-b86c-d58f0e49ec48

**Comment by chrisgorgo** [comment]
When you say "this error" what do you mean?

@nellh logs do not show up for https://openneuro.org/datasets/ds000109/versions/00001 https://openneuro.org/datasets/ds000110/versions/00001

**Comment by sadevp** [comment]
I am referring to this issue: https://github.com/OpenNeuroOrg/openneuro/issues/135
