### ISSUE TITLE
FAIL Exit Code 137 [fmriPREP]

### ISSUE THREAD

**Issue by sadevp** [OpenNeuroOrg/openneuro#151]
Referencing this dataset: https://openneuro.org/datasets/ds001031/versions/00001

In the error log, I am seeing an Exit Code 137 for three of the subjects. The logs read 'Job Finished' for those failed subjects, so I am ensure of where the error is stemming from. It is however, causing the fmriprep to fail for this dataset.

**Comment by chrisgorgo** [comment]
Some comments:
- This job was scheduled by a different user than yours - are you sure this is not a mixup?
- Subject 28 is missing functional data which seems to be a problem with the dataset (even on S3) @suyash please look into this. This is not listed in README as a known issue and _events files are present.
- This job has been scheduled last month - probably one of the jobs @nellh terminated recently.

I scheduled a new run with fresh FMRIPREP version (and exclusion of subejct 28 since it is not suppose to complete without BOLD data).

**Comment by nellh** [comment]
One thing that is confusing here is that exit codes passed up from inside the bids container are incremented by [128 - see the -e option](http://man7.org/linux/man-pages/man1/script.1.html). 1-128 means the error was outside the app container, 129-255 means inside. We could abstract this or just subtract 128 (giving negative error codes to Batch issues).

**Comment by chrisgorgo** [comment]
My rerun failed - again with error 137. I could not debug further due to #147 fix not being deployed in production.

**Comment by nellh** [comment]
@chrisfilo Have you been able to look at this now the logs are downloadable? It looks like an issue with the app but I'm not sure.

**Comment by chrisgorgo** [comment]
yes it works now. Thanks!

**Comment by chrisgorgo** [comment]
This seems to have happened once again: https://openneuro.org/datasets/ds001033/versions/00001?app=FMRIPREP&version=32&job=f0e26bac-f9ec-4c3c-a176-358d9ef4bbef

**Comment by nellh** [comment]
I think this is just the retry bug, where this status didn't get cleared on retry. This seems to be working otherwise and the retry fix is deployed in prod.
