### ISSUE TITLE
Metadata form unable to be submitted

### ISSUE THREAD

**Issue by franklin-feingold** [OpenNeuroOrg/openneuro#1516]
users using the CLI and then filling out the metadata form before they can publish their set is hanging on the metadata form submission. I was able to replicate this

**Comment by nellh** [comment]
Here's the error: `Variable "$metadata" got invalid value [] at "metadata.tasksCompleted"; Expected type String. String cannot represent a non string value: []`

Regression introduced in #1474 - looks like tasks (since they a derived field) need to be excluded from the mutation. This could also use a test to catch this in the future.

**Comment by franklin-feingold** [comment]
resolved via https://github.com/OpenNeuroOrg/openneuro/pull/1518 - confirmed metadata form is submittable
