### ISSUE TITLE
ds002653 still not downloadable 2 days after publishing

### ISSUE THREAD

**Issue by jbwexler** [OpenNeuroOrg/openneuro#1578]
I tried all four methods of downloading the dataset, none of which worked. And I can see that the dataset is not present in the openneuro.org s3 bucket. I should also note that the webpage still says "Validation Pending".

**Comment by nellh** [comment]
This turns out to affect any recently published datasets that did not already have remotes configured due to a change in git-annex. We rolled back to an earlier version of git-annex and the affected datasets are being pushed to S3 now but it will be a few days until all affected datasets are available. I'll close this issue once they are all synced.

**Comment by ckrountree** [comment]
Done...
