### ISSUE TITLE
Possible to update part of a dataset?

### ISSUE THREAD

**Issue by jcohenadad** [OpenNeuroOrg/openneuro#1652]
Hi,

I am managing a ~9GB dataset on openneuro ([ds002902](https://openneuro.org/datasets/ds002902/versions/1.0.0)). This dataset requires frequent update of sometimes a single file of a few kB. 

We are using the [CLI](https://github.com/OpenNeuroOrg/openneuro/blob/master/packages/openneuro-cli/README.md) to update the dataset, and looking at the log file, it seems like every time we run the `openneuro upload` command, the entire dataset is uploaded, which seems like a waste of bandwidth. 

Is there a way to only upload what has changed? (i.e. do the diff locally, before transferring).

Many thanks for maintaining this great infrastructure! 😃

**Comment by nellh** [comment]
Can you check that you are using the latest version of the CLI? There was a recent bug that broke skipping existing files for several releases but it was fixed in 3.12.3. The size of each file is checked and paths with the same size locally and on OpenNeuro should be skipped.

If you are on a newer release of the CLI and having this issue, what version of Node.js and platform (macOS, Linux, Windows) you are uploading from?

**Comment by jcohenadad** [comment]
ah! i am not using the latest version-- here is my version `3.6.0-rc.1`
i'm on OSX 10.14

i'll update and let you know how it goes. Thanks!

**Comment by jcohenadad** [comment]
working 👍
