### ISSUE TITLE
Add validation step to Datalad push support

### ISSUE THREAD

**Issue by ckrountree** [OpenNeuroOrg/openneuro#1893]

**Comment by effigies** [comment]
One question here is what happens when I have a dataset with subdatasets? e.g., If I'm creating derivatives for ds000001, I'll have a dataset like

```
ds000001-fmriprep/
    dataset_description.json
    sourcedata/
        ds000001//            # subdataset
        ds000001-freesurfer// # subdataset
    sub-01/
    ...
```

In our case, we would definitely not want to ingest ds000001, since we already have that dataset. We may on the other hand want to ingest ds000001-freesurfer and include it as part of this derivative rather than creating another full ON dataset and linking it.
