### ISSUE TITLE
Remove delete tool from unowned public datasets

### ISSUE THREAD

**Issue by david-nishi** [OpenNeuroOrg/openneuro#1923]
**Describe the bug**
The delete tool is visible on other's public datasets. It is not functional, but should be removed.

**To Reproduce**
1. Log in.
2. View a public dataset that isn't yours.

**Expected behavior**
The delete tool should not be available.

**Screenshots**
![dataset-toolbar](https://user-images.githubusercontent.com/28666458/104243016-ca987400-5414-11eb-914a-c54d91b4cbea.png)

**Desktop (please complete the following information):**
- [ ] Not applicable 
 - Browser [e.g. Chrome, Safari]

**Smartphone (please complete the following information):**
- [ ] Not applicable 

**Additional context**
*Add any other context about the problem here.*

**Comment by ckrountree** [comment]
### SPRINT REVIEW
Public datasets for users who are not the owners display the `delete` icon (and it will trigger the next display which allows the user to delete the dataset, although nothing will happen when the user tries to delete in this case).  This icon should be removed to eliminate confusion since the functionality does not (and should not) work.
![pre-delete](https://user-images.githubusercontent.com/27043528/107281456-8e096980-6a0e-11eb-90a4-c4dcfe0b9551.png)

Post-fix (no more `delete` icon):
![post-delete](https://user-images.githubusercontent.com/27043528/107281737-eb051f80-6a0e-11eb-9e55-860747d5febe.png)
