### ISSUE TITLE
Reject git push if new snapshots do not pass validation

### ISSUE THREAD

**Issue by nellh** [OpenNeuroOrg/openneuro#1955]
**Is your feature request related to a problem? Please describe.**
This will prevent BIDS-invalid snapshots from being pushed.

**Describe the solution you'd like**
Each new snapshot should be validated on push.

**Describe alternatives you've considered**
Invalid snapshots could be detected after the push and hidden or annotated on from the sidebar?

**Additional context**
May need to limit the number of snapshots that can be pushed at once to keep this performant.

**Comment by effigies** [comment]
> Invalid snapshots could be detected after the push and hidden or annotated on from the sidebar?

I think this might be the best option, considering that we have existing snapshots that do not validate due to updates to the validator. A consistent UX would be to continue to allow access but make validation failure evident in some way. The UI changes necessary here seem like they would dovetail with deprecation (#1136).

---

An additional concern is what happens with S3. Consider the case where a user makes a few versions internally, wants to publish, and pushes the latest 1.1.0 when they publish to OpenNeuro. Then they realize they have a reason to publish 1.0.0 (maybe they published a paper on that version).

Previously, I believe we would have had the issue that the latest snapshot would get pushed to the top of the stack of S3, and doing an AWS CLI sync would produce a dataset that is not identical to the latest snapshot. Is that resolved, or does that need to be considered in any tags that aren't latest `master`?

**Comment by ckrountree** [comment]
Can we allow invalid snapshots as long as they are backdated? Or maybe allow for a particular type of tag string to internally mark it? Perhaps, just note it in a tag.

It's conducive to run validation on multiple commits.  So hard to do at the git-hook level but we can throw them off into a queue and validate as resources become available - allow these pushes but if snapshot is invalid, we would note that later in the sidebar.

**Comment by nellh** [comment]
Closing this in favor of directing snapshot creation to OpenNeuro to keep the DOI process intact.
