### ISSUE TITLE
Keeping validation logs in elastic search

### ISSUE THREAD

**Issue by franklin-feingold** [OpenNeuroOrg/openneuro#1956]
**Is your feature request related to a problem? Please describe.**
Keeping our validation logs for longer than we currently store them

**Describe the solution you'd like**
Pushed to elastic search

**Comment by nellh** [comment]
This should collect the command output (stderr, stdout) when bids-validator fails to exit normally and annotate it with some metadata for what dataset it is, what user triggered the validation, and the exit status. This is written to ElasticSearch as a logs index for analyzing failures.

**Comment by nellh** [comment]
Adding some more specificity to this issue, it refers to failures that occur when bids-validator is run by the OpenNeuro backend service. Validator output is already captured in a Mongo collection but sometimes there's things like tracebacks or unhandled promise exceptions because of a bids-validator bug that we want to track to be able to look for any silent failures.

**Comment by ckrountree** [comment]
### sprint review
Nell will check in pre-release review.
