### ISSUE TITLE
Removing access to annex objects with privacy issues

### ISSUE THREAD

**Issue by ckrountree** [OpenNeuroOrg/openneuro#2003]
- Remove annexed objects, or hide them in case we want to keep track of the objects
- Mark files as a privacy issue (preventing doing DataLad get)
- Implement a database flag for a given file
- Admin capability (button)

**Comment by nellh** [comment]
To expand on the requirement here, this should be a site-admin visible button for annexed files that allows you to mark them as a privacy issue. This should add the annex key to a database collection and mark it for deletion. Immediately it should remove it from public replicas (S3). After a timeout or manual review, it should permanently delete the annexed object without modifying git history.

**Comment by effigies** [comment]
This button needs to be visible on releases, not just drafts, since a curator might update a dataset with a fixed image prior to the purge.

Also, xref https://github.com/datalad/datalad/issues/5478. Future versions of datalad or git-annex may give us the ability to publish revocation lists into the dataset metadata that mirrors (e.g., BrainLife) can use to purge PHI we detect.

**Comment by ckrountree** [comment]
Broke this out into frontend (#2018) and backend (#2019) tickets.
