### ISSUE TITLE
Uploading a dataset with a matching name does not resume correctly

### ISSUE THREAD

**Issue by nellh** [OpenNeuroOrg/openneuro#204]
If you have a dataset and try to upload one with the same name, this used to give you the option to resume or rename, but now it simply continues and this gets the upload modal into a bad state (mixed up tabs and such).

**Comment by Xesme** [comment]
The select folder button on step:3 will cause you to get stuck in a loop of choosing a folder as well.

**Comment by jstiehl** [comment]
I think I have the upload modal issues fixed with the same name dataset. The select folder button issue is a separate issue.  I noticed that if you just click back to step one at any time during the process and try to select files again the whole modal is broken. I will make a separate issue and work on that but wanted to PR the fix for upload with same name if you both are ok with that.

**Comment by jstiehl** [comment]
Nevermind, the select folder turned out to be an easy fix so it is included in the PR for this issue.
