### ISSUE TITLE
Job stuck in "Uploading"

### ISSUE THREAD

**Issue by chrisgorgo** [OpenNeuroOrg/openneuro#223]
https://openneuro.org/datasets/ds001158/versions/00001?app=MRIQC&version=50&job=5a1276a8921b110001c24502

**Comment by jstiehl** [comment]
It looks like the snapshot only partially got uploaded. 
![image](https://user-images.githubusercontent.com/5668826/33040046-c55367de-cdee-11e7-8a79-2fdb0a2e2bac.png)
I am trying to see if I can find any evidence of a failure during upload but I am having a little trouble. I do see that the dataset_description.json file never got tagged as upload completed. 

In the mean time, one option we could try is to delete the snapshot on s3 and manually kill the two jobs that are stuck and try again? Do you want to try that?

**Comment by chrisgorgo** [comment]
I don't have control over this dataset - it was submittted by another user. If you think restarting jobs would help please do it.

I am wondering if the unusual name of the dataset (which includes `.` and `-`) could cause upload problems.

**Comment by chrisgorgo** [comment]
https://neurostars.org/t/running-analyses-on-openneuro-status-is-stuck-on-uploading/1001/2

**Comment by jstiehl** [comment]
@chrisfilo Should I manually fail that other job that is stuck in uploading? Only issue with that is that the job will fail if a rerun is tried like in #225. 

This is the same issue with the snapshot upload to s3. I am trying to get ahold of Nell this AM to see if I can get some help on trying to figure out what is causing the issue. The worker seems to be crashing during the upload of the larger files and it is somewhat "silent" as to why. All I am seeing is "Killed" in the logs.

**Comment by chrisgorgo** [comment]
I don't think it would make sense to fail the job if we know restarting it will fail anyway.

Thanks for looking into this I hope this could be resolved soon.

**Comment by jstiehl** [comment]
OK so we figured out what the problem was. The worker container was running out of memory for the datasets with these large files.  When I bumped my docker memory locally to 8 GB I was able to run NARPS dataset with 2 subjects without any issues. I am testing a change to how we are reading in the files during snapshot upload now and assuming all that goes well I will get a deploy out today at some point.  The job that is currently stuck in uploading will have to be deleted and restarted when this change is deployed.

Mem usage during snapshot upload for the NARPS dataset run locally
![image](https://user-images.githubusercontent.com/5668826/33152214-6866c18a-cf90-11e7-91c0-2704bd88298b.png)
