### ISSUE TITLE
Add limited Safari support

### ISSUE THREAD

**Issue by nellh** [OpenNeuroOrg/openneuro#254]
Looks like a decent number of the client side errors we are seeing are from Safari users. Safari does not support all of the APIs required for the upload feature but it should be easy to fix crashes for Safari users so that they can at least browse the entire site.

**Comment by ckrountree** [comment]
@trevor this is a good place to start for the mobile improvements.

**Comment by nellh** [comment]
It still isn't possible to support uploads and browser-based downloads in Safari with the current implementation but it's likely a matter of CSS and polyfills to get everything else working.

**Comment by trevor-squishy** [comment]
@nellh When you say "get everything else working", what else is there besides uploads/downloads that is not working in Safari? There are general mobile fixes I am also working on, but those are not browser specific.

**Comment by nellh** [comment]
When this bug was originally filed there were JavaScript errors in Safari on the datasets page and the dashboard. If that's no longer the case for the dashboard, datasets page, or any of the toolbar pages, that's good - it just has not been tested in quite a while.

We are seeing some Safari specific Sentry errors still. https://sentry.io/organizations/openneuro/issues/1023706238/?project=251076&query=is%3Aunresolved+browser.name%3ASafari

**Comment by exbotanical** [comment]
Yep, this stuff is still an issue. Here's an overview: 

- Browser-based downloads appear to remain broken. When downloading datasets via Safari, the download.json is downloaded in lieu of the actual dataset (as is the case with the exact same datasets on Chrome). I'm not too familiar with Safari, but could this issue be similar to the MIME-type problem Safari had a while back? 
- Uploading remains unsupported. 
- There exist a few cosmetic issues, too, though this could be due to my deprecated version of Safari - the pop-up components for sign-in and upload are near-translucent.

**Comment by nellh** [comment]
Safari is basically working with improvements to Safari itself and cross browser fixes in various features on the site.
