### ISSUE TITLE
Dataset downloads do not provide file extension

### ISSUE THREAD

**Issue by chrisgorgo** [OpenNeuroOrg/openneuro#261]
Only happens for drafts. For https://openneuro.org/datasets/ds001179 suggested file is `TAUREST_BIDS_old ` instead of `TAUREST_BIDS_old.tar`

**Comment by nellh** [comment]
It looks like this is Firefox interpreting the content-disposition header more strictly than Chrome. @chrisfilo Just to confirm, were you seeing this in Firefox? poldracklab/bids-core#18 should fix this if it is the Firefox issue.

**Comment by chrisgorgo** [comment]
This was on chrome.

Best,
Chris

**Comment by nellh** [comment]
This dataset specifically has a newline character in the label which is causing this issue `TAUREST_BIDS_old\n`. Looks like the bids-core fixes other datasets seeing this problem on Firefox but for a different reason.

@chrisfilo Is there a reason for supporting multi-line labels? I think this should be a single line editor instead of multiple lines to prevent this issue.

**Comment by chrisgorgo** [comment]
Yes sanitizing titles to single lines sounds like a better approach.

Best,
Chris
