### ISSUE TITLE
Upgrade to 2017.09.d ECS optimized AMI

### ISSUE THREAD

**Issue by nellh** [OpenNeuroOrg/openneuro#263]
This will update the ECS agent and Docker to the latest supported versions for Batch and hopefully solves some issues with the agent failing to report state changes.

**Comment by nellh** [comment]
@chrisfilo I'm testing this upgrade on dev with a change to 500GB EBS space per instance from 1TB. Looking at the last couple weeks of disk usage in CloudWatch, we're not getting near the 500GB limit.

**Comment by chrisgorgo** [comment]
Sounds good!

Best,
Chris

On Dec 12, 2017 7:08 PM, "Nell Hardcastle" <notifications@github.com> wrote:

@chrisfilo <https://github.com/chrisfilo> I'm testing this upgrade on dev
with a change to 500GB EBS space per instance from 1TB. Looking at the last
couple weeks of disk usage in CloudWatch, we're not getting near the 500GB
limit.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/OpenNeuroOrg/openneuro/issues/263#issuecomment-351237438>,
or mute the thread

**Comment by nellh** [comment]
I'm waiting on some fmriprep test subjects to finish still but otherwise no issues with this. I'll update the production compute environment with the next release.
