### ISSUE TITLE
Link to NeuroBagel search

### ISSUE THREAD

**Issue by effigies** [OpenNeuroOrg/openneuro#2956]
### What would you like to see added?

As mentioned in https://github.com/OpenNeuroOrg/openneuro/issues/2807#issuecomment-1843598606, we can link to https://query.neurobagel.org/?node=OpenNeuro. "Annotated search" seems like a good name to indicate that this search is benefiting from third-party annotations. We could use the following text as an expansion:

> [NeuroBagel](https://neurobagel.org/) is a collection of tools for harmonizing metadata annotations, searching across datasets and constructing cohorts from multiple source datasets.

### Alternatives

* Directly query NeuroBagel API. This would take more time to do, and seems worth pushing off.

### Do you have any interest in helping implement the feature?

Yes, but I would need guidance

**Comment by surchs** [comment]
Thanks @effigies! I think the description should also include something on "participant-level" search to make it clear that you can find a cohort of participants that match, not just the datasets. 

How about
> Annotated participant search

for the search link.

For the neurobagel description I would also add this like so:
> [NeuroBagel](https://neurobagel.org/) is a collection of tools for harmonizing phenotypic and imaging data, searching for participants across datasets and constructing cohorts from multiple source datasets.

@alyssadai and @rmanaem, anything I missed?

**Comment by alyssadai** [comment]
Hi @surchs and @effigies,

The revised description is looking good! I would just correct the capitalization of "NeuroBagel" to "Neurobagel".

Also, to differentiate what Neurobagel does from any kind of statistical harmonization (which might be the default interpretation for folks in the neuroimaging community), I suggest the following edit:

> [Neurobagel](https://neurobagel.org/) is a collection of tools for harmonizing phenotypic and imaging data descriptions, searching for participants across datasets, and constructing cohorts from multiple source datasets.

**Comment by effigies** [comment]
@alyssadai LGTM. Thanks for the suggestion!

**Comment by surchs** [comment]
Hey folks, 

@effigies mentioned that you'd be open to a PR from us to add this link. We looked through the codebase and came up with two options that I think we can implement (mostly) with existing components.

Because the "You can search at the participant level" link is not part of the search parameters container, I think it fits more on the search side of the UI. Let us know if you agree with the overall positioning.

## Option 1 - text link with accordion component
![accordion_option](https://github.com/OpenNeuroOrg/openneuro/assets/1302022/023a22ad-4881-422f-bcbf-25e316c08ffb)

I think we could reuse the [accordion-wrapper](https://github.com/OpenNeuroOrg/openneuro/blob/2f451f549aeb58b17be433cb744e7516a1ca4c93/packages/openneuro-components/src/accordion/AccordionWrap.tsx) component together with a plain text link. The little `?` thing would sit on the right of the link and when clicked, expand a text box with the context information - analogous to what happens on the keyword search. We would probably have to add a bit to the stylesheet so the position of the `?` works with the longer text.

## Option 2 - dropdown with context information inside
![dropdown_option](https://github.com/OpenNeuroOrg/openneuro/assets/1302022/f86d7ea5-3364-4ce6-8c48-9af707c9f131)

We could also reuse the [dropdown component](https://github.com/OpenNeuroOrg/openneuro/blob/2f451f549aeb58b17be433cb744e7516a1ca4c93/packages/openneuro-components/src/dropdown/Dropdown.tsx)  and when a user clicks on it they would see the context and link - similar to how the "Clone dataset" workflow works on the dataset page. 

Let us know what you think / prefer. I think we could find some time this or next week to make a draft PR after that.

**Comment by effigies** [comment]
Of these two, I prefer option 1.

**Comment by surchs** [comment]
Sounds good @effigies, we'll prepare a PR in that case and then can discuss the rest there.
