### ISSUE TITLE
uploading ds005295 using openneuro CLI

### ISSUE THREAD

**Issue by vassiki** [OpenNeuroOrg/openneuro#3104]
### Dataset issue

I am using the OpenNeuro CLI to upload a dataset that I would like to make public, but I was only able to upload a few json files. The dataset passess BIDS validation, but shows up with errors on the OpenNeuro website due to an incomplete upload.

Here is the command I am using:

`openneuro upload -i -n --dataset ds005295 path_to_my_bids_ds`

I tried the upload without the -n flag, but it didn't make a difference for what I see on OpenNeuro's website.

Is there a way to continue adding to this dataset without changing the accession number?  

### Expected behavior
My BIDS dataset shows up on OpenNeuro website as a valid dataset, and I am able to release it publicly.

### How to reproduce
With the upload command.

### Desktop
OS: MacOS Sonoma 14.4.1
Browser: Google Chrome
Version: OpenNeuro CLI 4.25.0

### The following datasets are affected

- [ ] ds005295

**Comment by nellh** [comment]
Could you let me know what version of Node.js you're using? That would help narrow this down.

You could also try our new CLI in the meantime. One major difference is this uses the BIDS schema based validator, you may run into a slightly different set of validation issues depending on your dataset. This uploader uses Deno ([install instructions](https://deno.com/)) instead of Node.js. Once you have Deno, the commands are similar:

```
# Login with your OpenNeuro API key
deno run -A https://deno.land/x/openneuro@v4.25.0/openneuro.ts login
# Upload
deno run -A https://deno.land/x/openneuro@v4.25.0/openneuro.ts upload -d ds005295 path_to_my_bids_ds
```

This should also resume the partial upload you have already started if you use an identical local copy of the dataset. It will take some time to hash large files before the upload resumes, there is an open issue (#3022) to implement a progress indicator for this.

**Comment by vassiki** [comment]
Thanks for the quick response. The Node.js version I'm using is v20.15.0. I will attempt the upload with Deno instead.

**Comment by vassiki** [comment]
I'd trying the upload using deno with the following command

`deno run -A https://deno.land/x/openneuro@v4.25.0/openneuro.ts upload --dataset ds005295 path_to_my_bids_ds`

but I get a too many arguments error, where `path_to_my_bids_ds` is seen is an extra argument. I also tried to navigate to my BIDS directory, and simply provide the dataset accension number without the path, but there I got a NotFound error (os error 2). is that because the dataset isn't public?

**Comment by nellh** [comment]
> I'd trying the upload using deno with the following command
> 
> `deno run -A https://deno.land/x/openneuro@v4.25.0/openneuro.ts upload --dataset ds005295 path_to_my_bids_ds`
> 
> but I get a too many arguments error, where `path_to_my_bids_ds` is seen is an extra argument. I also tried to navigate to my BIDS directory, and simply provide the dataset accension number without the path, but there I got a NotFound error (os error 2). is that because the dataset isn't public?

Thanks for trying it. Can you give `https://deno.land/x/openneuro@v4.26.1/openneuro.ts` a try? It should resolve the argument length bug you're seeing.

**Comment by nellh** [comment]
Looks like this has been resolved? Please reopen if you're still having issues here.
