### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by chrisgorgo** [OpenNeuroOrg/openneuro#32]
When trying to load https://openneuro.org/datasets/ds001049

```
Uncaught TypeError: Cannot read property 'length' of undefined
    at t.value (/app.min.4f999727.js:50)
    at t.value (/app.min.4f999727.js:50)
    at t.value (/app.min.4f999727.js:50)
    at c._renderValidatedComponentWithoutOwnerOrContext (/app.min.4f999727.js:38)
    at c._renderValidatedComponent (/app.min.4f999727.js:38)
    at c.mountComponent (/app.min.4f999727.js:37)
    at Object.mountComponent (/app.min.4f999727.js:40)
    at v.mountChildren (/app.min.4f999727.js:39)
    at v._createContentMarkup (/app.min.4f999727.js:38)
    at v.mountComponent (/app.min.4f999727.js:38)
```

We have a user stuck on this - it would be great to get it fixed in a timely manner.

**Comment by chrisgorgo** [comment]
Happened after user tried to delete one of the .nii files.

**Comment by nellh** [comment]
Looks like they deleted the only .nii file and that's important because it leads to a special case where the validator returns 'Invalid' instead of a list of errors.

I'm writing tests and a fix for this on the frontend but maybe it would be better to remove this special case from the validator? It would be more consistent to return a regular validator error [quickTest fails](https://github.com/INCF/bids-validator/blob/master/validators/bids.js#L44).

**Comment by nellh** [comment]
Last step to finish this is to upgrade OpenNeuro to bids-validator@0.23

**Comment by nellh** [comment]
@chrisfilo The bids-validator fixes prevent this from crashing the page but it is still impossible to recover from it. You can't add a subject because the directory is removed automatically and you can't create directories. You can delete the dataset and start over with these fixes and it's much clearer what went wrong with the error code.

Should we support adding subjects after upload so you can recover from this situation without recreating the dataset?

**Comment by chrisgorgo** [comment]
Yes. Adding new subjects after upload is very useful when you run apps while still acquiring data.

**Comment by chrisgorgo** [comment]
Even after update this error is still affecting this dataset. Maybe revalidation needs to be forced?

In addition, there is a new one as well now:
```
Uncaught TypeError: Cannot read property 'body' of undefined
    at scitran.js:169
    at o (request.js:131)
    at request.js:26
    at u.callback (client.js:615)
    at u.<anonymous> (client.js:415)
    at u.t.emit (index.js:133)
    at XMLHttpRequest.e.onreadystatechange (client.js:705)
```

**Comment by chrisgorgo** [comment]
The second error is probably https://github.com/OpenNeuroOrg/openneuro/issues/6

**Comment by chrisgorgo** [comment]
I confirmed the original error on a connection not affected by #6

**Comment by nellh** [comment]
@chrisfilo I did miss revalidating this in my deployment steps. I just tried it now and ran into a problem with the dataset hashes not matching up. I'll put together a workaround tomorrow.

**Comment by nellh** [comment]
@chrisfilo I cleared the bad validation data but it looks like this dataset was deleted. Revalidation didn't work since the files are missing.
