### ISSUE TITLE
Follow dataset feature

### ISSUE THREAD

**Issue by chrisgorgo** [OpenNeuroOrg/openneuro#337]
Users should be able to "follow" a dataset and thus receive email notifications about:

- new snapshots of the dataset (the email should include the change log if included - see #327)
- new comments and replies (the email should include the content of the message - related to #328)

Users should be encourage to follow a dataset when clicking the download button.

**Comment by olgn** [comment]
- submitters should be automatically following to the datasets they upload
- during/before downloading a dataset users should be encourage to follow a dataset
- there should be information on each dataset (for example above comments) if its submitter is still following it

PS I prefer the term "following" instead of "subscribing" because latter has a bad connotation of "subscription fees" common in academia.
