### ISSUE TITLE
Jobs should automatically be stopped after 48 hours

### ISSUE THREAD

**Issue by nellh** [OpenNeuroOrg/openneuro#37]
Jobs running for more than 48 hours should be failed automatically to prevent stuck or very resource intense jobs from running indefinitely.

**Comment by chrisgorgo** [comment]
We have a few more jobs hanging indefinitely due to lack of this constraint. They were hard to debug because cloud watch logs seemed to be purged.

**Comment by nellh** [comment]
@chrisfilo CloudWatch should keep logs until the compute environment is recreated. Maybe these jobs never started? Logs are not created until it enters the running state. I have seen this with some jobs that hung the host container but not recently.

**Comment by chrisgorgo** [comment]
Here's an example of a recent job that I terminated because it run too long
https://console.aws.amazon.com/batch/home?region=us-east-1#/jobs/queue/arn:aws:batch:us-east-1:488777458602:job-queue~2Fopenneuro-prod/state/FAILED/job/e996ae5a-cab2-405a-99f0-941da4e7bedc/queue/arn:aws:batch:us-east-1:488777458602:job-queue~2Fopenneuro-prod/state/FAILED


The longs do not seem to be present in cloud watch, but maybe I am missing
something.

**Comment by nellh** [comment]
@chrisfilo Ah, I see what's going on. When Amazon changed the CloudWatch log names, they didn't fix the Batch UI, so that button in Batch is currently broken. You can find them but it's a pain, you have to search for something like `FMRIPREP/default/<taskARN>` which is not a value you can see without making API calls.

**Comment by chrisgorgo** [comment]
Ok - thanks for the clarification!

**Comment by chrisgorgo** [comment]
One of our apps is running into a deadlock issue and runs forever. It would be great to increase the priority of this feature.

**Comment by chrisgorgo** [comment]
Having the major performance bottle neck solved I would like to propose prioritizing this issue:

- we are seeing users confused by jobs running for days
- those jobs are also consuming resources

Since bids-core performance has improved maybe this issue https://github.com/OpenNeuroOrg/openneuro/issues/109 could be replaced by the 48h cutoff one in the current sprint. @JohnKael
