### ISSUE TITLE
Dataset subscriptions

### ISSUE THREAD

**Issue by olgn** [OpenNeuroOrg/openneuro#373]
users should be able to subscribe to datasets and / or dataset comments. 

activity on the dataset / comment to which a user is subscribed will generate an email notification containing information about that activity. 

users should be able to unsubscribe via the app. 

email notifications are required by law to contain a link that unsubscribes the user from the notification system.

**Comment by chrisgorgo** [comment]
- submitters should be automatically following to the datasets they upload
- during/before downloading a dataset users should be encourage to follow a dataset
- there should be information on each dataset (for example above comments) if its submitter is still following it

PS I prefer the term "following" instead of "subscribing" because latter has a bad connotation of "subscription fees" common in academia.

**Comment by olgn** [comment]
this is actually already an older ticket. closing this and keeping the former - copying this comment to #337 and pointing comment on #328 to the proper ticket.
