### ISSUE TITLE
On ds000117

### ISSUE THREAD

**Issue by gllmflndn** [OpenNeuroOrg/openneuro#549]
I have been looking at [ds000117](https://openneuro.org/datasets/ds000117/versions/00002) and have a few comments. They should possibly be spread across several issues, sorry for keeping them under a single umbrella.

- `Size: 11.36GB`: the .tar file I downloaded was 130GB (more about that below).
- ` Subjects: 17, Sessions: 10`: there are 16 subjects with 2 sessions each and 1 subject with 8 sessions. I find aggregate statistics a bit misleading here.
- `Available Modalities`: `meg` is missing.

When downloading the dataset, its length is unspecified in the HTTP header; Would it be possible to add a `Content-Length` field?

The file I downloaded through my browser (`Multisubject multimodal face processing_20180409_093952.tar`, 139066917076 bytes) seems corrupted and I could only extract the 17 first files followed by "Damaged tar archive"). I'm trying to download it again from the command line using the URL https://openneuro.org/api/snapshots/download?ticket=xxx-xxx-xxx-xxx that I obtained from the link of the green arrow. It saves a file "download?ticket=xxx". Could a different filename be proposed through a `Content-Disposition` HTTP header, such as `ds000117_v00002.tar`? At last, all the files seem to be stored within a `Multisubject, multimodal face processing` directory, could that be something like `ds000117_v00002` instead?

**Comment by nellh** [comment]
Hi, thanks for the feedback!

We'll look into the size discrepancy - this could be related to an issue with the validator reporting incorrect sizes due to .bidsignore.

@chrisfilo Do you have feedback on how sessions should be counted in this case?

We'll also look into the issue with the reported modalities.

Content-Length is not set in the current implementation because we generate the archive dynamically, the length is unknown before we start sending data. There is a new dataset backend in progress that will resolve this.

Did you download this with Firefox? There is an open issue for larger downloads from Firefox (#316) we will be addressing soon. Chrome should work in the meantime.

Content-Disposition is set with a filename in the `Multisubject multimodal face processing_20180409_093952.tar` format. What tool were you using to download via the ticket link? It is difficult to download with a URL outside of a browser, I'll add an issue for adding download support to our new CLI tool (it is focused on uploading first).

**Comment by gllmflndn** [comment]
Thank you, very useful.

I am indeed using Firefox. Will try again with Chromium.

From the command line, I used `wget` and it seems the file is corrupted too (and 68GB) with only 17 files extracted.

**Comment by chrisgorgo** [comment]
- the incorrect download size is an issue that should be solved (see https://github.com/OpenNeuroOrg/openneuro/issues/391) - could be that this snapshot needs to be revalidated?
- not sure what is up with the missing 'meg' modality - are you seeing this with the current version of the standalone validator http://incf.github.io/bids-validator/ ? If so could you open an issue at https://github.com/INCF/bids-validator/issues
- the incorrect number of subjects/session is due to the `sub-emptyroom` - I opened an issue to ignore this subject when counting sessions/subjects https://github.com/INCF/bids-validator/issues/453

**Comment by gllmflndn** [comment]
I tried again with Chromium 65.0.3325.181 and it seems the downloaded file is identical to the one I obtained with Firefox (same size and same error with tar).

@chrisfilo How does one revalidate a snapshot? Also, about the missing `meg` modality, I refer to what is indicated on the [webpage](https://openneuro.org/datasets/ds000117/versions/00002) of the dataset: is this directly related to the validator?

**Comment by chrisgorgo** [comment]
The fact that you still experience issues when using Chrome is troubling.

Revalidating a snapshot would need to be triggered, by updating the dataset and creating a new snapshot - alternatively maybe @nellh could trigger it behind the scenes.

Dataset size, number or participants/sessions and list of tasks/modalities is coming directly from the validator which is developed independently.

**Comment by gllmflndn** [comment]
Tried to download it again last night with Chromium but got the same file (139066917076 bytes, md5sum 33cde10c37dbe2979df0f7af2959da64). Could someone else try and download the snapshot of v2?

**Comment by nellh** [comment]
@gllmflndn I think we've fixed the download issue you were seeing here, the archive creation was broken for datasets containing zero length files (related issue #562). The affected file is `derivatives/meg_derivatives/ct_sparse.fif` in ds000117. Please give downloading another try.

**Comment by gllmflndn** [comment]
Thanks @nellh , download went fine this time and I could extract all the files from the archive.

As my other comments are now opened elsewhere, this issue can be closed.
