### ISSUE TITLE
Incorrect snapshot IDs and empty page

### ISSUE THREAD

**Issue by chrisgorgo** [OpenNeuroOrg/openneuro#619]
When logged out https://openneuro.org/datasets/ds000107 leads to a redirect to https://openneuro.org/datasets/ds000107/versions/00002 and
```
app-fe0d8443.bundle.js:1 GET https://openneuro.org/api/users 403 ()
(anonymous) @ app-fe0d8443.bundle.js:1
u._end @ app-fe0d8443.bundle.js:5
u.end @ app-fe0d8443.bundle.js:5
(anonymous) @ app-fe0d8443.bundle.js:5
n.then @ app-fe0d8443.bundle.js:5
```

```
app-fe0d8443.bundle.js:1 GET https://openneuro.org/api/snapshots/projects/3030303130372d3030303032 404 ()
(anonymous) @ app-fe0d8443.bundle.js:1
u._end @ app-fe0d8443.bundle.js:5
u.end @ app-fe0d8443.bundle.js:5
(anonymous) @ app-fe0d8443.bundle.js:5
n.then @ app-fe0d8443.bundle.js:5
XMLHttpRequest.send (async)
(anonymous) @ app-fe0d8443.bundle.js:1
u._end @ app-fe0d8443.bundle.js:5
u.end @ app-fe0d8443.bundle.js:5
(anonymous) @ app-fe0d8443.bundle.js:5
n.then @ app-fe0d8443.bundle.js:5
```

Rendering the page empty and inaccessible.

From an admin perspective I see two snapshots
v1: https://openneuro.org/datasets/ds000107/versions/58054c33cce88d000ca33620
v2: https://openneuro.org/datasets/ds000107/versions/00001 (yes - v2 is under 0001)

Clearly there is something wrong with snapshot IDs. When fixing this please make sure there are no more dataset in such state.

**Comment by olgn** [comment]
@chrisfilo we have fixed the snapshot redirect link with #620. attempting to access a dataset that one does not have access to will now properly redirect to the most recent available snapshot. the snapshot version syncing issue (v2 appearing having the url 0001) is a side-effect due to scitran, and will be taken care of when the backend is replaced.

**Comment by olgn** [comment]
@chrisfilo you are correct, this was a dataset redirect issue, not an accessibility issue. we were trying to redirect to the wrong path, based on snapshot_version rather than snapshot._id (we hadn't noticed this bug because there are hardly any datasets that have snapshot_version out of sync with snapshot._id)

**Comment by chrisgorgo** [comment]
awesome - thank you!
