### ISSUE TITLE
Use BIDS app versions instead of OpenNeuro app versions

### ISSUE THREAD

**Issue by chrisgorgo** [OpenNeuroOrg/openneuro#62]
https://gitlab.sqm.io/stanford_crn/openneuro/issues/190

Temporary workaround https://github.com/OpenNeuroOrg/openneuro/issues/61

**Comment by nellh** [comment]
Since one part of this (the host container versions) is fixed, clarifying this to be the move from using Batch definition versions to key jobs to using the bids-version and creating any Batch definitions needed implicitly.

| Tag | Old | New |
| -- | -- | -- |
| poldracklab/fmriprep:1.0.0-rc6 | v:20 | 1.0.0-rc6 |
| poldracklab/fmriprep:1.0.0-rc6 | v:19 | 1.0.0-rc6 |
| poldracklab/fmriprep:0.6.5 | v:18 | 0.6.5 |
| poldracklab/fmriprep:0.6.3 | v:17 | 0.6.3 |
| poldracklab/fmriprep:0.6.3 | v:16 | 0.6.3 |

These Batch versions will still exist API side but will be created whenever the template differs instead of manually.
