### ISSUE TITLE
Please make message "please upgrade to a newer supported browser" more informative

### ISSUE THREAD

**Issue by yarikoptic** [OpenNeuroOrg/openneuro#732]
I am using Firefox EST 52.7.2 on Debian, while trying to download a dataset from https://openneuro.dev.sqm.io/datasets/ds001116 I am given a message that 

Your browser is out of date, please upgrade to a newer supported browser to download.

It would be nice if minimal requirements were presented right there so I knew how new I need to become ;-)

**Comment by nellh** [comment]
Ah, there's a link missing. This is supposed to direct you to the FAQ which has instructions for enabling support on Firefox.

**Comment by nellh** [comment]
I've updated this message with "Your browser must support service workers to download. See the FAQ for supported browsers."

Firefox 52 should support service workers though, so I'm surprised you are getting this message. Most of the site requires these: `{ chrome: '49', chromium: '49', firefox: '50' }` Downloads are special since we're creating the bundles browser side and this is only possible for large datasets with web streams, which is not yet stable in Firefox.

**Comment by ftadel** [comment]
I'm getting this error message with Firefox 61.0.2 on Win10.
Property "dom.ipc.multiOptOut" does not exist on this version.
