### ISSUE TITLE
Add googlebot compatibility checks to CI

### ISSUE THREAD

**Issue by chrisgorgo** [OpenNeuroOrg/openneuro#814]
https://medium.com/ovrsea/headless-browser-testing-with-jest-and-puppeteer-2cf7d04f4af5

https://developers.google.com/web/tools/puppeteer/articles/ssr

googlebot currently uses chrome 41, but puppeteer requires headless mode which is implemented in 59 upwards: https://stackoverflow.com/questions/49176356/puppeteer-with-old-chrome-versions

**Comment by nellh** [comment]
I think we should close this because of the complexity of simulating Googlebot. The most recent issue wouldn't have been reproducible with a Chrome 41 integration test, since Chrome 41 supports websockets but Googlebot doesn't. It may be worth revisiting when Googlebot has moved to a version of headless Chrome we can add end to end tests for.

Instead we should monitor the search indexing performance on a regular basis.
