### ISSUE TITLE
Corrupted snapshot

### ISSUE THREAD

**Issue by chrisgorgo** [OpenNeuroOrg/openneuro#883]
![image](https://user-images.githubusercontent.com/238759/45229570-06d2cd00-b27b-11e8-86ef-22c9335aea13.png)
https://openneuro.org/datasets/ds001505

This goes away after navigating to the snapshot landing page and back to draft

**Comment by chrisgorgo** [comment]
Actually I was wrong - there is something wrong with https://openneuro.org/datasets/ds001505/versions/2.0.1 snapshot

**Comment by nellh** [comment]
Couple bugs here, there's a crash because an error is handled wrong in getSnapshots. Then the underlying error is the snapshot resolver makes a bad assumption about public datasets, that they will always have been exported to S3 already. The fallback used for private datasets should be used for public ones as well until they have finished exporting. This dataset has finished exporting but we're still seeing this because the cache can't update if the snapshot resolver doesn't run.

I'll fix these and push 2.2.1, this will affect any new snapshots of public datasets.
