### ISSUE TITLE
openneuro-cli should warn when it is out of date

### ISSUE THREAD

**Issue by nellh** [OpenNeuroOrg/openneuro#886]
We should at least show a message if you are using a different major version and maybe not allow users with an out of date major version (CLI 2.1 with server 2.2).

**Comment by nellh** [comment]
To implement this, we should add an OpenNeuro key to extensions returned with each request. This would include a version key with the server side version. The client can then compare this key on any request and if it is too old (defined as minor version mismatch) it should warn the user they should upgrade.

A request looks like this:
```json
{
  "data": {
    "dataset": {
      "id": "ds00001"
    }
  },
  "extensions": {
    "openneuro": {
      "version": "3.10.1"
    }
  }
}
```

[Here's some discussion on how to add a custom extension.](https://spectrum.chat/apollo/apollo-server/writing-custom-extensions-any-good-docs~7541a8fd-668a-4050-9afc-ddeecc9f7b12)

I don't think we want to prevent users from using an old client, just prompt them that upgrading may improve things. In general the API has been fairly good about being forward compatible, so minor versions often do not break things.

**Comment by david-nishi** [comment]
@nellh and I have discussed some unexpected complications. To summarize: 

Package versions for client, app, and cli may not always match the server version due to lerna not publishing packages with no changes, so checking for out-of-date packages reliably means checking the server version against that of the app or cli and (for now) manually ensuring that all three packages are published together regardless of whether or not they have changes.

Ideally, we should contain all of the API logic to the client package. This would better separate concerns and allow us to resolve this issue by a simple comparison between the server and client versions.
